<a href="https://colab.research.google.com/github/sohan1423/Numpy_full_practice_course/blob/main/Py_numpy_practice_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [106]:
import numpy as np


In [107]:
np.array([1,3])

array([1, 3])

#Dimention

In [108]:

arr = np.array([[[]]])
arr.ndim
arr.shape

(1, 1, 0)

In [109]:
range = np.arange(1,10,2)  # start , stop, step
range

array([1, 3, 5, 7, 9])

In [110]:
arr = np.linspace(0,2,5)   #start, stop , num of value between start and stop
arr

array([0. , 0.5, 1. , 1.5, 2. ])

In [111]:
arr = np.logspace(1,3,4)  #logarithomic ---10^1  to 10^3 ----between 4 points
arr

array([  10.        ,   46.41588834,  215.443469  , 1000.        ])

In [112]:
arr = np.zeros(5)  # print num of zero in array which I want
arr

array([0., 0., 0., 0., 0.])

In [113]:
arr = np.zeros([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [114]:
arr = np.ones([3,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [115]:
arr = np.full([2,4],4)  #(dim [], value )
arr

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [116]:
arr = np.random.rand(2,3) # create random value using dim --no need square baraket
arr

array([[0.74278959, 0.91805916, 0.51288081],
       [0.99835521, 0.64076662, 0.00120129]])

In [117]:
arr = np.random.randn(2,3)  # also take neg value
arr

array([[-0.50313334,  0.80242188,  0.58325167],
       [ 0.81393536,  0.92173534,  1.62507438]])

In [118]:
arr = np.random.randint(10,89, (2,4)) # random int-------->basically range (start , stop) -----size means dim
arr

array([[20, 32, 18, 36],
       [42, 74, 88, 57]])

In [119]:
arr = np.array([
                  [1,3,2],
                  [3,5,7],
                  [3,5,8]
                ])
print("Here the matrix")
print(arr)  # if I write print that erase the array write which wrote the sytem by default

Here the matrix
[[1 3 2]
 [3 5 7]
 [3 5 8]]


#data type and type casting

# we can't convert string to int or float its called casting error

In [120]:
arr = np.array([1,3,3,4])
arr.dtype

dtype('int64')

In [121]:
arr = np.array([1,3,3,4], dtype = np.float64)
arr.dtype

dtype('float64')

In [122]:
# ----->type casting====> astype()

arr = np.array([1,3,4])
arr.dtype

dtype('int64')

In [123]:
new_arr = arr.astype(np.float64)
new_arr

array([1., 3., 4.])

In [124]:
new_arr.dtype

dtype('float64')

#Arary Re-shaping -------->Re-shape, Ravel, Flatten

In [125]:


arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)
reshaped



array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

r = arr.ravel()
print("Original:\n", arr)
print("Raveled:", r)

# Change element in ravel
r[0] = 99
print("After change, Original:\n", arr)


Original:
 [[1 2 3]
 [4 5 6]]
Raveled: [1 2 3 4 5 6]
After change, Original:
 [[99  2  3]
 [ 4  5  6]]


In [127]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

f = arr.flatten()
print("Flattened:", f)

# Change element in flatten
f[0] = 99
print("After change, Flattened:", f)
print("Original:\n", arr)


Flattened: [1 2 3 4 5 6]
After change, Flattened: [99  2  3  4  5  6]
Original:
 [[1 2 3]
 [4 5 6]]


#Arithmetic operation


In [128]:
a = np.array([1,2,3])
b = np.array([4,5,6])


In [129]:
print(a+b)

[5 7 9]


In [130]:
print(a-b)

[-3 -3 -3]


In [131]:
print(b-a)

[3 3 3]


In [132]:
print(a/b) # // for int division

[0.25 0.4  0.5 ]


In [133]:
print(a*b)

[ 4 10 18]


In [134]:
# reminder
print(b%a)

[0 1 0]


In [135]:
#exponent ->  power
print(a**b)

[  1  32 729]


# universal fuction -----> ufuncs


---



In [136]:
arr = np.array([1,4,9,16])


In [137]:
#square root -->n.sqrt()
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [138]:
#exponential --> np.exp-->e^x
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [139]:
#sine function

angles = np.array([0,np.pi/2,np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


#indexing and  scilicing

In [140]:
# neg indexing
a = [1,2,3,4,5]


In [141]:
a[-1:-4:  -1]  #last -1 help to print neg indexing otherwise print the empty set

[5, 4, 3]

In [142]:
a[: : 2] # skip value

[1, 3, 5]

In [143]:
#applied in numpy array
arr = np.array([1,2,3,4,5,6,7])
arr[ : : 2]

array([1, 3, 5, 7])

In [144]:
# neg indexing
print(arr[-2])


6


#multi dim arry slicinf

In [145]:
matrix =  np.array([
    [1,2,3],[4,5,6],[7,8,9]
])

In [146]:
print(matrix[1:3 , 1:3])

[[5 6]
 [8 9]]


In [147]:
#Advance indexing ---->Build in function to perfoem indexing and sclicing
arr = np.array([1,2,3,4,5,6,7])
a = [0,2]
print(np.take(arr,a))

[1 3]


#Iterating with nditer

In [148]:
arr =([
    [1,2], [3,4]
])


In [149]:
for x in np.nditer(arr):
  print(x, end = " ")

(array(1), array(3)) (array(2), array(4)) 

#views vs Copy

In [150]:
arr = np.array([1,2,3,4,5,6])
view = arr[1:6]    # when we cnanges view is[3]----its range will effect

view


array([2, 3, 4, 5, 6])

In [151]:
view[2] = 200

In [152]:
arr

array([  1,   2,   3, 200,   5,   6])

In [153]:
copy = arr[1:3].copy()
copy

array([2, 3])

#Transpose

In [154]:
arr  = np.array([[1,3],[4,5]])
arr

array([[1, 3],
       [4, 5]])

In [155]:
print(arr.transpose())

[[1 4]
 [3 5]]


#swapaxes--> swap 2 specific access

In [156]:
arr = np.array([[[1,2],[3,4]]])
arr.shape

(1, 2, 2)

In [157]:
swap = np.swapaxes(arr,0,1)
swap.shape

(2, 1, 2)

#concatenation

In [158]:
a = np.array([2,4])
b = np.array([5,6])



In [159]:
combine = np.concatenate((a,b))
combine

array([2, 4, 5, 6])

In [160]:
# v starck -other way o omplement (vertical stack)
arr1  = np.array([[1,2], [3,4]])
arr2  = np.array([[5,6], [7,8]])


In [161]:
print(np.vstack((arr1,arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [162]:
#h stack-------(horizontal stack )
print(np.hstack((arr1,arr2)))


[[1 2 5 6]
 [3 4 7 8]]


In [163]:
print(np.stack((arr1,arr2), axis = 0))  #row wise

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [164]:
print(np.stack((arr1,arr2), axis = 1))    #  join coloumn wise

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [165]:
#Repeating :
arr =  np.array([1,2,3])
print(np.repeat(arr,2))

[1 1 2 2 3 3]


In [166]:
#tile----repeating whole array
print(np.tile(arr,3))

[1 2 3 1 2 3 1 2 3]


In [167]:
#Aggregate function
arr = np.array([1,2,3])
print(np.sum(arr))

6


In [168]:
np.mean(arr)

np.float64(2.0)

In [169]:
np.median(arr)

np.float64(2.0)

In [170]:
#standard division
np.std(arr)

np.float64(0.816496580927726)

In [171]:
#variance
np.var(arr)

np.float64(0.6666666666666666)

In [172]:
np.min(arr)

np.int64(1)

In [173]:
np.max(arr)

np.int64(3)

In [174]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [175]:
#sum column wise or row wise
print(np.sum(matrix, axis = 0)) #row sum
print(np.sum(matrix, axis = 1)) #coloumn sum

[12 15 18]
[ 6 15 24]


In [176]:
#cumulative operation -----> runing total
arr


array([1, 2, 3])

In [177]:
print(np.cumsum(arr))

[1 3 6]


In [178]:
print(np.cumprod(arr))# 1, 1*2=2, 1*2*3=6

[1 2 6]


In [179]:
#where
arr

array([1, 2, 3])

In [180]:
result = np.where(arr < 2, "low", "high")

In [181]:
result

array(['low', 'high', 'high'], dtype='<U4')

In [182]:
#logical and
arr = np.array([100,2,3,4,5,6])

In [183]:
arr

array([100,   2,   3,   4,   5,   6])

In [184]:
mask = np.logical_and(arr > 3, arr < 6)

In [185]:
mask # 4 = true ,5= true otherwise false

array([False, False, False,  True,  True, False])

In [186]:
arr[mask]

array([4, 5])

In [187]:
#logical or
mask = np.logical_or(arr < 4, arr>5)

In [188]:
mask

array([ True,  True,  True, False, False,  True])

In [189]:
arr[mask]

array([100,   2,   3,   6])

# Broadcasting

In [190]:
img = np.array([[200,250],[100,250]])
img

array([[200, 250],
       [100, 250]])

In [191]:
brightness = img + 100

In [192]:
brightness

array([[300, 350],
       [200, 350]])

In [193]:
img.shape

(2, 2)

In [194]:
brightness.shape

(2, 2)

In [195]:
#vectorization
# np.vertorize()------> convert a regular function to be applied on ana array


In [196]:
def square(x):
  return x*x
vfunc = np.vectorize(square)


In [197]:
arr

array([100,   2,   3,   4,   5,   6])

In [198]:
print(vfunc(arr))

[10000     4     9    16    25    36]


#Dealing with missing values
##  np.nan-----> not a number

In [199]:
a = np.array([1,2,np.nan,4])

In [200]:
a

array([ 1.,  2., nan,  4.])

In [201]:
# np.ing  and -np.inf------>possitive and neg infinite values
# np.isnan
# np.isinf
# np.isfinite

#--------> Used to the function to detect null values, infinite values and finite values

In [202]:
print(np.isnan(a))

[False False  True False]


In [203]:
print(np.isinf(a))

[False False False False]


In [204]:
print(np.isfinite(a))

[ True  True False  True]


In [205]:
b = np.array([1,2,3,np.inf,5])

In [206]:
print(np.isinf(b))

[False False False  True False]
